### ISSUE TITLE
hautelook/phpass package with version 0.3.4

### ISSUE THREAD

**Issue by adiyya** [mikemclin/laravel-wp-password#10]
Hi Thanks for Great Package.

I have a small issue to use with this package.

The package currently using 'hautelook/phpass' version '0.0.3'

I need '**hautelook/phpass**' package version '**0.3.4**'

Any plans to update this to new version?

Thanks,
@adiyya

**Comment by mikemclin** [comment]
I was unable to verify which version of `hautelook/phpass` WordPress was using.  It just said `0.3` in the `class-phpass.php` file.  So, I changed to version requirements in my `composer.json` file to use a wildcard for the patch version.  This should allow you to use `0.3.4` if you'd like.

**Comment by adiyya** [comment]
Hi,

I need this package to use hautelook/phpass version 0.3.4

How can I use this with above version?

Thanks,
- Adi

**Comment by adiyya** [comment]
I have plan to use this package with corcel package.

Corcel package using hautelook/phpass version 0.3.4

Any idea how to use this?

Thanks,
- Adi

**Comment by mikemclin** [comment]
Run `composer remove mikemclin/laravel-wp-password` to remove the package.

Then, reinstall the package by running `composer require mikemclin/laravel-wp-password`.  This should install the version compatible with your application.

**Comment by adiyya** [comment]
Thanks Mike for the patch. It worked like charm!!

Adi
