### ISSUE TITLE
Wordpress 5.4 & Laravel 7.0

### ISSUE THREAD

**Issue by jrson83** [mikemclin/laravel-wp-password#12]
Is the Plugin still working with the current versions?
I have setup everything correct but in my listener, no matter what I try, ` WpPassword::check` does not return true.

```
public function handle(Failed $event)
    {
      $user = User::where('email',$event->credentials['email'])->first();

      if ( $user ) {
        Log::debug($user->password);
        if ( WpPassword::check($event->credentials['password'], $user->password ) ) {
          Auth::login($user);

          $user->password = Hash::make($event->credentials['password']);
          $user->save();

        }
      }
    }
```

**Comment by mikemclin** [comment]
To be honest, I don't know.  I haven't used Laravel since version 5.  I had accepted a pull request the other day for someone that wanted to update the README file, to say that it supports those versions.  So, I assume it does.  I'll keep this open to let someone else possibly chime in.

**Comment by gpressutto5** [comment]
I don't know about WordPress 5.4, but I can guarantee this package does work with Laravel 7, I tested it using WordPress 4.8.2:

```php
>>> WpPassword::check('password', '$P$BWA.KOcrJq1c37OBYAF1Nrq5hghmOn1')
=> true
>>> WpPassword::check('wrong-password', '$P$BWA.KOcrJq1c37OBYAF1Nrq5hghmOn1')
=> false
```

**Comment by jrson83** [comment]
I tried to generate a hash for wordpress v3 & v4 on the [website](https://www.useotools.com/wordpress-password-hash-generator/).

test => $P$BFxodsh7rUVtko3SCqGiF8zWlWTiGF.

I replaced the users hash in the database with the new generated hash and the login is working.
I also registered a new user with password "test" on wordpress v5 and copied the hash from the wp_users table to the laravel users table. The login is also working.

The original password includes " and ', can this maybe be an the problem?

**Comment by gpressutto5** [comment]
Does the original password start with `$P$`? Can you post it here? You can hide part of it if you want.
Does it work when logging in on WordPress?
Maybe it got corrupted when migrating? Maybe the script you used to migrate the tables didn't properly escape the `"` and `'`?

**Comment by jrson83** [comment]
The hash is: $P$Bw0ueLTMt3k2pN9oGyjJz/jzLAAf6t/

It works when logging into wordpress. I exported the wp_users and migrated it in laravel, and the hash looks the same, in both tables. Even if i copy the hash from the original wordpress and past it into the laravel table, the login doesn't work.

**Comment by jrson83** [comment]
I found out the problem. There was a quotation mark in the password and I did not escape propperly before calling the function `WpPassword::check`. I tested manually and escaped the mark with `\"` in the password input login form and it worked. So `addslashes($event->credentials['password']);` did the trick. I hope this doesn't create other issues with other passwords.
Thanks for the help.
