### ISSUE TITLE
hautelook/phpass is now a 404 which causes problems

### ISSUE THREAD

**Issue by bordoni** [mikemclin/laravel-wp-password#13]
This repo has a dependency on `hautelook/phpass` which seems to have been deleted.
https://github.com/hautelook/phpass

Only exists on Packagist.
https://packagist.org/packages/hautelook/phpass

I've created a fork of the original to solve the problem we were facing on The Events Calendar.
https://github.com/bordoni/phpass

See the PRs where this was applied:
https://github.com/the-events-calendar/tribe-common/pull/1652
https://github.com/the-events-calendar/the-events-calendar/pull/3639

**Comment by vladbndko** [comment]
Got same problem today

**Comment by zmilonas** [comment]
It might be possible to work around it with aliases. 

https://getcomposer.org/doc/articles/aliases.md

**Comment by bordoni** [comment]
For now: `composer require bordoni/phpass` if you are using Composer 2.x will work.
Tonight the above will work for composer 1.x too

**Comment by mikebertiean** [comment]
This has caused a massive outage for us. Time to reconsider the libraries being used :\

**Comment by bordoni** [comment]
Note that the Composer version 1 is available now. No more need to use `repositories`.

**Comment by vladbndko** [comment]
@mikebertiean Hi, I created [PR](https://github.com/mikemclin/laravel-wp-password/pull/14) with updated composer.json, where I:
- In satooshi/php-coveralls updated version `dev-master` to `^2.2`.
- Replaced `hautelook/phpass 0.3.*` dependency with `bordoni/phpass dev-main`.

**Comment by cliffordp** [comment]
FYI: https://www.openwall.com/phpass/ is an old-looking website that says you should avoid using the package if you can. Maybe the 404 was intentional? Surprisingly, their https://www.hautecode.io/ site is down as well.

I understand _this_ repo can work with Laravel 4 which can run on PHP 5.4 and lesser, for which `phpass` was required. Maybe the longer-term goal is for this repo to not support Laravel versions that are so old. Not a vote either way, just sharing an observation, like @mikebertiean said.

Thanks, @bordoni - good to see you here helping all of us ;)

**Comment by mikemclin** [comment]
I have merged everything in and tagged a new release.  Thanks for all of the help!

**Comment by seostudio** [comment]
Hi, don't works with `"minimum-stability": "stable"`.

**Comment by foxyphil** [comment]
Hi All! 

I'm struggling a bit here. I'm trying to install munkireoport with this documentation https://www.froggtech.com/blog/2020/1/24/how-to-setup-munkireport-on-ubuntu-1804

Looks like there is also a dependency to this as well. What exactly do I need to change in composer.lock? I'm a novice so any advice would be super appreciated. I've been at this for over half a day and i'm starting to lose it. lol

**Comment by mikemclin** [comment]
@foxyphil I haven't touched a PHP project in several years, but I can tell you that the `composer.lock` file is generated and should not be edited manually.

**Comment by foxyphil** [comment]
Got it! Thanks @mikemclin That was very helpful! I'm back up and running.
